-- Drop the primary key constraint first (this will also drop the underlying index)
alter table "public"."interactions" drop constraint if exists "interactions_pkey";

-- Change type to bigint first (must be integer type before adding identity)
alter table "public"."interactions" alter column "interaction_id" set data type bigint using "interaction_id"::bigint;

-- Now add identity
alter table "public"."interactions" alter column "interaction_id" add generated by default as identity;

CREATE UNIQUE INDEX interactions_interaction_id_key ON public.interactions USING btree (interaction_id);

-- Recreate primary key constraint
alter table "public"."interactions" add constraint "interactions_pkey" primary key (interaction_id);

alter table "public"."interactions" add constraint "interactions_interaction_id_key" UNIQUE using index "interactions_interaction_id_key";


-- Migration: Add RPC function for retrieving last K interactions grouped by request
-- This function retrieves the most recent K interactions for a user and their associated
-- request data, used for sliding window extraction.

-- Drop existing function first since return type is changing (interaction_id: text -> bigint)
DROP FUNCTION IF EXISTS public.get_last_k_interactions(text, integer);

CREATE OR REPLACE FUNCTION public.get_last_k_interactions(
    p_user_id text,
    p_limit int
)
RETURNS TABLE(
    request_id text,
    request_user_id text,
    request_created_at timestamp with time zone,
    request_source text,
    request_agent_version text,
    request_group text,
    interaction_id bigint,
    interaction_user_id text,
    interaction_content text,
    interaction_request_id text,
    interaction_created_at timestamp with time zone,
    interaction_role text,
    interaction_user_action text,
    interaction_user_action_description text,
    interaction_interacted_image_url text,
    interaction_shadow_content text
)
LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    WITH last_k_interactions AS (
        SELECT i.*
        FROM interactions i
        WHERE i.user_id = p_user_id
        ORDER BY i.interaction_id DESC
        LIMIT p_limit
    )
    SELECT
        r.request_id,
        r.user_id as request_user_id,
        r.created_at as request_created_at,
        r.source as request_source,
        r.agent_version as request_agent_version,
        r.request_group,
        lki.interaction_id,
        lki.user_id as interaction_user_id,
        lki.content as interaction_content,
        lki.request_id as interaction_request_id,
        lki.created_at as interaction_created_at,
        lki.role as interaction_role,
        lki.user_action as interaction_user_action,
        lki.user_action_description as interaction_user_action_description,
        lki.interacted_image_url as interaction_interacted_image_url,
        lki.shadow_content as interaction_shadow_content
    FROM last_k_interactions lki
    INNER JOIN requests r ON lki.request_id = r.request_id
    ORDER BY lki.interaction_id DESC;
END;
$function$;


-- Migration: Add RPC function for efficient request-interaction retrieval
-- This function performs a single JOIN query to get new interactions grouped by request,
-- filtering by timestamp and excluding already-processed interaction IDs.

-- Drop existing function first since return type is changing (interaction_id: text -> bigint)
DROP FUNCTION IF EXISTS public.get_new_request_interaction_groups(text, timestamp with time zone, text[]);

CREATE OR REPLACE FUNCTION public.get_new_request_interaction_groups(
    p_user_id text,
    p_last_processed_timestamp timestamp with time zone DEFAULT NULL,
    p_excluded_interaction_ids bigint[] DEFAULT ARRAY[]::bigint[]
)
RETURNS TABLE(
    request_id text,
    request_user_id text,
    request_created_at timestamp with time zone,
    request_source text,
    request_agent_version text,
    request_group text,
    interaction_id bigint,
    interaction_user_id text,
    interaction_content text,
    interaction_request_id text,
    interaction_created_at timestamp with time zone,
    interaction_role text,
    interaction_user_action text,
    interaction_user_action_description text,
    interaction_interacted_image_url text,
    interaction_shadow_content text
)
LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        r.request_id,
        r.user_id as request_user_id,
        r.created_at as request_created_at,
        r.source as request_source,
        r.agent_version as request_agent_version,
        r.request_group,
        i.interaction_id,
        i.user_id as interaction_user_id,
        i.content as interaction_content,
        i.request_id as interaction_request_id,
        i.created_at as interaction_created_at,
        i.role as interaction_role,
        i.user_action as interaction_user_action,
        i.user_action_description as interaction_user_action_description,
        i.interacted_image_url as interaction_interacted_image_url,
        i.shadow_content as interaction_shadow_content
    FROM requests r
    INNER JOIN interactions i ON r.request_id = i.request_id
    WHERE r.user_id = p_user_id
      AND i.user_id = p_user_id
      AND (p_last_processed_timestamp IS NULL OR i.created_at >= p_last_processed_timestamp)
      AND NOT (i.interaction_id = ANY(p_excluded_interaction_ids))
    ORDER BY i.interaction_id ASC;
END;
$function$;
