create extension if not exists "vector" with schema "public";

create sequence "public"."profile_change_logs_id_seq";


  create table "public"."_operation_state" (
    "service_name" text not null,
    "operation_state" jsonb not null default '{}'::jsonb,
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."agent_success_evaluation_result" (
    "result_id" bigint generated by default as identity not null,
    "request_id" character varying not null,
    "created_at" timestamp without time zone not null default now(),
    "agent_version" character varying,
    "is_success" boolean,
    "failure_type" character varying,
    "failure_reason" text,
    "agent_prompt_update" text,
    "embedding" public.vector
      );



  create table "public"."feedbacks" (
    "feedback_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "feedback_content" text not null,
    "feedback_status" text not null,
    "agent_version" text,
    "feedback_metadata" text,
    "status" text,
    "embedding" public.vector,
    "feedback_name" text
      );



  create table "public"."interactions" (
    "user_id" text not null,
    "content" text not null,
    "shadow_content" text,
    "request_id" text,
    "user_action" text not null,
    "user_action_description" text,
    "interacted_image_url" text,
    "embedding" public.vector(1536),
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "interaction_id" text not null
      );



  create table "public"."profile_change_logs" (
    "id" integer not null default nextval('public.profile_change_logs_id_seq'::regclass),
    "created_at" integer not null,
    "user_id" character varying not null,
    "request_id" character varying not null,
    "added_profiles" json,
    "removed_profiles" json,
    "mentioned_profiles" json
      );



  create table "public"."profiles" (
    "user_id" text not null,
    "content" text not null,
    "last_modified_timestamp" bigint not null,
    "generated_from_request_id" text,
    "profile_time_to_live" text not null,
    "expiration_timestamp" bigint not null,
    "custom_features" json,
    "embedding" public.vector(1536),
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "profile_id" text not null,
    "source" character varying,
    "status" text
      );



  create table "public"."raw_feedbacks" (
    "raw_feedback_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "request_id" text not null,
    "agent_version" text,
    "feedback_content" text,
    "embedding" public.vector,
    "feedback_name" text,
    "status" text
      );



  create table "public"."requests" (
    "request_id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "source" text,
    "agent_version" text,
    "user_id" text not null,
    "request_group" text
      );


alter sequence "public"."profile_change_logs_id_seq" owned by "public"."profile_change_logs"."id";

CREATE UNIQUE INDEX agent_success_evaluation_result_request_id_key ON public.agent_success_evaluation_result USING btree (request_id);

alter table "public"."agent_success_evaluation_result" add constraint "agent_success_evaluation_result_request_id_key" UNIQUE using index "agent_success_evaluation_result_request_id_key";

CREATE UNIQUE INDEX _operation_state_pkey ON public._operation_state USING btree (service_name);

CREATE UNIQUE INDEX _operation_state_service_name_key ON public._operation_state USING btree (service_name);

CREATE UNIQUE INDEX agent_success_evaluation_result_pkey ON public.agent_success_evaluation_result USING btree (result_id);

CREATE UNIQUE INDEX feedbacks_pkey ON public.feedbacks USING btree (feedback_id);

CREATE INDEX interactions_embedding_idx ON public.interactions USING ivfflat (embedding public.vector_cosine_ops) WITH (lists='100');

CREATE UNIQUE INDEX interactions_pkey ON public.interactions USING btree (interaction_id);

CREATE INDEX interactions_user_id_idx ON public.interactions USING btree (user_id);

CREATE INDEX ix_profile_change_logs_id ON public.profile_change_logs USING btree (id);

CREATE INDEX ix_profile_change_logs_request_id ON public.profile_change_logs USING btree (request_id);

CREATE UNIQUE INDEX profile_change_logs_pkey ON public.profile_change_logs USING btree (id);

CREATE INDEX profiles_embedding_idx ON public.profiles USING ivfflat (embedding public.vector_cosine_ops) WITH (lists='100');

CREATE INDEX profiles_expiration_timestamp_idx ON public.profiles USING btree (expiration_timestamp);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (profile_id);

CREATE INDEX profiles_user_id_idx ON public.profiles USING btree (user_id);

CREATE UNIQUE INDEX raw_feedbacks_pkey ON public.raw_feedbacks USING btree (raw_feedback_id);

CREATE UNIQUE INDEX requests_pkey ON public.requests USING btree (request_id);

alter table "public"."_operation_state" add constraint "_operation_state_pkey" PRIMARY KEY using index "_operation_state_pkey";

alter table "public"."agent_success_evaluation_result" add constraint "agent_success_evaluation_result_pkey" PRIMARY KEY using index "agent_success_evaluation_result_pkey";

alter table "public"."feedbacks" add constraint "feedbacks_pkey" PRIMARY KEY using index "feedbacks_pkey";

alter table "public"."interactions" add constraint "interactions_pkey" PRIMARY KEY using index "interactions_pkey";

alter table "public"."profile_change_logs" add constraint "profile_change_logs_pkey" PRIMARY KEY using index "profile_change_logs_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."raw_feedbacks" add constraint "raw_feedbacks_pkey" PRIMARY KEY using index "raw_feedbacks_pkey";

alter table "public"."requests" add constraint "requests_pkey" PRIMARY KEY using index "requests_pkey";

alter table "public"."_operation_state" add constraint "_operation_state_service_name_key" UNIQUE using index "_operation_state_service_name_key";

alter table "public"."interactions" add constraint "interactions_request_id_fkey" FOREIGN KEY (request_id) REFERENCES public.requests(request_id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."interactions" validate constraint "interactions_request_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.match_feedbacks(query_embedding public.vector, match_threshold double precision, match_count integer)
 RETURNS TABLE(feedback_id bigint, feedback_name text, feedback_content text, feedback_status text, agent_version text, feedback_metadata text, created_at timestamp with time zone, similarity double precision, embedding public.vector)
 LANGUAGE plpgsql
AS $function$
begin
    return query
    select
        feedbacks.feedback_id,
        feedbacks.feedback_name,
        feedbacks.feedback_content,
        feedbacks.feedback_status,
        feedbacks.agent_version,
        feedbacks.feedback_metadata,
        feedbacks.created_at,
        1 - (feedbacks.embedding <=> query_embedding) as similarity,
        feedbacks.embedding
    from feedbacks
    where 1 - (feedbacks.embedding <=> query_embedding) > match_threshold
    order by feedbacks.embedding <=> query_embedding
    limit match_count;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.match_interactions(query_embedding public.vector, match_threshold double precision, match_count integer)
 RETURNS TABLE(interaction_id text, user_id text, content text, request_id text, created_at timestamp with time zone, user_action text, user_action_description text, interacted_image_url text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
begin
    return query
    select
        interactions.interaction_id,
        interactions.user_id,
        interactions.content,
        interactions.request_id,
        interactions.created_at,
        interactions.user_action,
        interactions.user_action_description,
        interactions.interacted_image_url,
        1 - (interactions.embedding <=> query_embedding) as similarity
    from interactions
    where 1 - (interactions.embedding <=> query_embedding) > match_threshold
    order by interactions.embedding <=> query_embedding
    limit match_count;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.match_profiles(query_embedding public.vector, match_threshold double precision, match_count integer, current_epoch bigint)
 RETURNS TABLE(profile_id text, user_id text, content text, last_modified_timestamp bigint, generated_from_request_id text, profile_time_to_live text, expiration_timestamp bigint, custom_features json, source character varying, similarity double precision)
 LANGUAGE plpgsql
AS $function$begin
    return query
    select
        profiles.profile_id,
        profiles.user_id,
        profiles.content,
        profiles.last_modified_timestamp,
        profiles.generated_from_request_id,
        profiles.profile_time_to_live,
        profiles.expiration_timestamp,
        profiles.custom_features,
        profiles.source,
        1 - (profiles.embedding <=> query_embedding) as similarity
    from profiles
    where profiles.expiration_timestamp >= current_epoch
    and 1 - (profiles.embedding <=> query_embedding) > match_threshold
    order by profiles.embedding <=> query_embedding
    limit match_count;
end;$function$
;

CREATE OR REPLACE FUNCTION public.match_raw_feedbacks(query_embedding public.vector, match_threshold double precision, match_count integer)
 RETURNS TABLE(raw_feedback_id bigint, feedback_name text, request_id text, agent_version text, feedback_content text, created_at timestamp with time zone, similarity double precision, embedding public.vector)
 LANGUAGE plpgsql
AS $function$
begin
    return query
    select
        raw_feedbacks.raw_feedback_id,
        raw_feedbacks.feedback_name,
        raw_feedbacks.request_id,
        raw_feedbacks.agent_version,
        raw_feedbacks.feedback_content,
        raw_feedbacks.created_at,
        1 - (raw_feedbacks.embedding <=> query_embedding) as similarity,
        raw_feedbacks.embedding
    from raw_feedbacks
    where 1 - (raw_feedbacks.embedding <=> query_embedding) > match_threshold
    order by raw_feedbacks.embedding <=> query_embedding
    limit match_count;
end;
$function$
;

grant delete on table "public"."_operation_state" to "anon";

grant insert on table "public"."_operation_state" to "anon";

grant references on table "public"."_operation_state" to "anon";

grant select on table "public"."_operation_state" to "anon";

grant trigger on table "public"."_operation_state" to "anon";

grant truncate on table "public"."_operation_state" to "anon";

grant update on table "public"."_operation_state" to "anon";

grant delete on table "public"."_operation_state" to "authenticated";

grant insert on table "public"."_operation_state" to "authenticated";

grant references on table "public"."_operation_state" to "authenticated";

grant select on table "public"."_operation_state" to "authenticated";

grant trigger on table "public"."_operation_state" to "authenticated";

grant truncate on table "public"."_operation_state" to "authenticated";

grant update on table "public"."_operation_state" to "authenticated";

grant delete on table "public"."_operation_state" to "service_role";

grant insert on table "public"."_operation_state" to "service_role";

grant references on table "public"."_operation_state" to "service_role";

grant select on table "public"."_operation_state" to "service_role";

grant trigger on table "public"."_operation_state" to "service_role";

grant truncate on table "public"."_operation_state" to "service_role";

grant update on table "public"."_operation_state" to "service_role";

grant delete on table "public"."agent_success_evaluation_result" to "anon";

grant insert on table "public"."agent_success_evaluation_result" to "anon";

grant references on table "public"."agent_success_evaluation_result" to "anon";

grant select on table "public"."agent_success_evaluation_result" to "anon";

grant trigger on table "public"."agent_success_evaluation_result" to "anon";

grant truncate on table "public"."agent_success_evaluation_result" to "anon";

grant update on table "public"."agent_success_evaluation_result" to "anon";

grant delete on table "public"."agent_success_evaluation_result" to "authenticated";

grant insert on table "public"."agent_success_evaluation_result" to "authenticated";

grant references on table "public"."agent_success_evaluation_result" to "authenticated";

grant select on table "public"."agent_success_evaluation_result" to "authenticated";

grant trigger on table "public"."agent_success_evaluation_result" to "authenticated";

grant truncate on table "public"."agent_success_evaluation_result" to "authenticated";

grant update on table "public"."agent_success_evaluation_result" to "authenticated";

grant delete on table "public"."agent_success_evaluation_result" to "service_role";

grant insert on table "public"."agent_success_evaluation_result" to "service_role";

grant references on table "public"."agent_success_evaluation_result" to "service_role";

grant select on table "public"."agent_success_evaluation_result" to "service_role";

grant trigger on table "public"."agent_success_evaluation_result" to "service_role";

grant truncate on table "public"."agent_success_evaluation_result" to "service_role";

grant update on table "public"."agent_success_evaluation_result" to "service_role";

grant delete on table "public"."feedbacks" to "anon";

grant insert on table "public"."feedbacks" to "anon";

grant references on table "public"."feedbacks" to "anon";

grant select on table "public"."feedbacks" to "anon";

grant trigger on table "public"."feedbacks" to "anon";

grant truncate on table "public"."feedbacks" to "anon";

grant update on table "public"."feedbacks" to "anon";

grant delete on table "public"."feedbacks" to "authenticated";

grant insert on table "public"."feedbacks" to "authenticated";

grant references on table "public"."feedbacks" to "authenticated";

grant select on table "public"."feedbacks" to "authenticated";

grant trigger on table "public"."feedbacks" to "authenticated";

grant truncate on table "public"."feedbacks" to "authenticated";

grant update on table "public"."feedbacks" to "authenticated";

grant delete on table "public"."feedbacks" to "service_role";

grant insert on table "public"."feedbacks" to "service_role";

grant references on table "public"."feedbacks" to "service_role";

grant select on table "public"."feedbacks" to "service_role";

grant trigger on table "public"."feedbacks" to "service_role";

grant truncate on table "public"."feedbacks" to "service_role";

grant update on table "public"."feedbacks" to "service_role";

grant delete on table "public"."interactions" to "anon";

grant insert on table "public"."interactions" to "anon";

grant references on table "public"."interactions" to "anon";

grant select on table "public"."interactions" to "anon";

grant trigger on table "public"."interactions" to "anon";

grant truncate on table "public"."interactions" to "anon";

grant update on table "public"."interactions" to "anon";

grant delete on table "public"."interactions" to "authenticated";

grant insert on table "public"."interactions" to "authenticated";

grant references on table "public"."interactions" to "authenticated";

grant select on table "public"."interactions" to "authenticated";

grant trigger on table "public"."interactions" to "authenticated";

grant truncate on table "public"."interactions" to "authenticated";

grant update on table "public"."interactions" to "authenticated";

grant delete on table "public"."interactions" to "service_role";

grant insert on table "public"."interactions" to "service_role";

grant references on table "public"."interactions" to "service_role";

grant select on table "public"."interactions" to "service_role";

grant trigger on table "public"."interactions" to "service_role";

grant truncate on table "public"."interactions" to "service_role";

grant update on table "public"."interactions" to "service_role";

grant delete on table "public"."profile_change_logs" to "anon";

grant insert on table "public"."profile_change_logs" to "anon";

grant references on table "public"."profile_change_logs" to "anon";

grant select on table "public"."profile_change_logs" to "anon";

grant trigger on table "public"."profile_change_logs" to "anon";

grant truncate on table "public"."profile_change_logs" to "anon";

grant update on table "public"."profile_change_logs" to "anon";

grant delete on table "public"."profile_change_logs" to "authenticated";

grant insert on table "public"."profile_change_logs" to "authenticated";

grant references on table "public"."profile_change_logs" to "authenticated";

grant select on table "public"."profile_change_logs" to "authenticated";

grant trigger on table "public"."profile_change_logs" to "authenticated";

grant truncate on table "public"."profile_change_logs" to "authenticated";

grant update on table "public"."profile_change_logs" to "authenticated";

grant delete on table "public"."profile_change_logs" to "service_role";

grant insert on table "public"."profile_change_logs" to "service_role";

grant references on table "public"."profile_change_logs" to "service_role";

grant select on table "public"."profile_change_logs" to "service_role";

grant trigger on table "public"."profile_change_logs" to "service_role";

grant truncate on table "public"."profile_change_logs" to "service_role";

grant update on table "public"."profile_change_logs" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."raw_feedbacks" to "anon";

grant insert on table "public"."raw_feedbacks" to "anon";

grant references on table "public"."raw_feedbacks" to "anon";

grant select on table "public"."raw_feedbacks" to "anon";

grant trigger on table "public"."raw_feedbacks" to "anon";

grant truncate on table "public"."raw_feedbacks" to "anon";

grant update on table "public"."raw_feedbacks" to "anon";

grant delete on table "public"."raw_feedbacks" to "authenticated";

grant insert on table "public"."raw_feedbacks" to "authenticated";

grant references on table "public"."raw_feedbacks" to "authenticated";

grant select on table "public"."raw_feedbacks" to "authenticated";

grant trigger on table "public"."raw_feedbacks" to "authenticated";

grant truncate on table "public"."raw_feedbacks" to "authenticated";

grant update on table "public"."raw_feedbacks" to "authenticated";

grant delete on table "public"."raw_feedbacks" to "service_role";

grant insert on table "public"."raw_feedbacks" to "service_role";

grant references on table "public"."raw_feedbacks" to "service_role";

grant select on table "public"."raw_feedbacks" to "service_role";

grant trigger on table "public"."raw_feedbacks" to "service_role";

grant truncate on table "public"."raw_feedbacks" to "service_role";

grant update on table "public"."raw_feedbacks" to "service_role";

grant delete on table "public"."requests" to "anon";

grant insert on table "public"."requests" to "anon";

grant references on table "public"."requests" to "anon";

grant select on table "public"."requests" to "anon";

grant trigger on table "public"."requests" to "anon";

grant truncate on table "public"."requests" to "anon";

grant update on table "public"."requests" to "anon";

grant delete on table "public"."requests" to "authenticated";

grant insert on table "public"."requests" to "authenticated";

grant references on table "public"."requests" to "authenticated";

grant select on table "public"."requests" to "authenticated";

grant trigger on table "public"."requests" to "authenticated";

grant truncate on table "public"."requests" to "authenticated";

grant update on table "public"."requests" to "authenticated";

grant delete on table "public"."requests" to "service_role";

grant insert on table "public"."requests" to "service_role";

grant references on table "public"."requests" to "service_role";

grant select on table "public"."requests" to "service_role";

grant trigger on table "public"."requests" to "service_role";

grant truncate on table "public"."requests" to "service_role";

grant update on table "public"."requests" to "service_role";
