-- Create feedback_aggregation_change_logs table
-- Tracks before/after state of each feedback aggregation run

CREATE TABLE IF NOT EXISTS "public"."feedback_aggregation_change_logs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" integer NOT NULL,
    "feedback_name" text NOT NULL,
    "agent_version" text NOT NULL,
    "run_mode" text NOT NULL,
    "added_feedbacks" jsonb,
    "removed_feedbacks" jsonb,
    "updated_feedbacks" jsonb
);

CREATE INDEX IF NOT EXISTS idx_feedback_agg_change_logs_name_version
    ON "public"."feedback_aggregation_change_logs" ("feedback_name", "agent_version");

CREATE INDEX IF NOT EXISTS idx_feedback_agg_change_logs_created_at
    ON "public"."feedback_aggregation_change_logs" ("created_at" DESC);
